- hosts: all
  vars:
          api_user: root@pam
          api_password : vault_password
          api_host : 192.168.200.128
  tasks:
       - name: "Test-VM"
         proxmox_kvm:
             api_user    : "{{ api_user }}"
             api_password: "{{ api_password }}"
             api_host    : "{{ api_host }}"
             name        : TestVM
             node        : nodeproxmox1
             ide         : '{"ide0":"local:iso/ubuntu-18.04.1-live-server-amd64.iso,media=disk"}'
             memory      : 2048
             cores       : 2
